<?php
return array(
	'group'=>array(
		'type'=>'group',
		'options'=>array(
			'setting'=>array(
				'title'=>'设置',
				'options'=>array(
					'domain'=>array(
						'title'=>'注册域名:',
						'type'=>'text',
						'value'=>'localhost',
						'tip'=>'在线版用户输入在nextalk.im中注册的域名'
					),
					'apikey'=>array(
						'title'=>'注册ApiKey:',
						'type'=>'text',
						'value'=>'public',
					),
					'host'=>array(
						'title'=>'IM服务器:',
						'type'=>'text',
						'value'=>'nextalk.im',
					),
					'port'=>array(
						'title'=>'IM服务器端口：',
						'type'=>'text',
						'value'=>'8000',
					),
					'local'=>array(
						'title'=>'本地语言:',
						'type'=>'select',
						'options'=>array(
							'zh-CN'=>'简体中文',
							'zh-TW'=>'繁体中文',
							'en'=>'English',
						),
						'value'=>'zh-CN',
					),
					'emot'=>array(
						'title'=>'表情：',
						'type'=>'text',
						'value'=>'default',
					),
					'opacity'=>array(
						'title'=>'工具条透明度:',
						'type'=>'text',
						'value'=>'80',
					),
					'opacity'=>array(
						'title'=>'工具条透明度:',
						'type'=>'text',
						'value'=>'80',
					),
					'enable_room'=>array(
						'title'=>'关闭群组聊天:',
						'type'=>'radio',
						'options'=>array(
							'0'=>'是',
							'1'=>'否',
						),
						'value'=>'1',
					),
					'enable_chatlink'=>array(
						'title'=>'关闭陌生人聊天:',
						'type'=>'radio',
						'options'=>array(
							'0'=>'是',
							'1'=>'否',
						),
						'value'=>'0',
					),
					'show_realname'=>array(
						'title'=>'显示真实姓名:',
						'type'=>'radio',
						'options'=>array(
							'1'=>'是',
							'0'=>'否',
						),
						'value'=>'0',
					),
					'enable_menu'=>array(
						'title'=>'隐藏菜单:',
						'type'=>'radio',
						'options'=>array(
							'0'=>'是',
							'1'=>'否',
						),
						'value'=>'0',
					),
				)
			),
			'theme'=>array(
				'title'=>'主题',
				'options'=>array(
					'theme'=>array(
						'title'=>'清除历史',
						'type'=>'hidden',
						'value'=>'base'
					)
				)
			),
			'history'=>array(
				'title'=>'清除历史',
				'options'=>array(
					'ago'=>array(
						'title'=>'清除历史：',
						'type'=>'select',
						'options'=>array(
							'weekago'=>'清除一周前历史',
							'monthago'=>'清除一月前历史',
							'3monthago'=>'清除三月前历史'
						),
					)
				)
			)
		)
	)
);
